// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api_pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/golang/protobuf/ptypes/struct"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	_ "google.golang.org/genproto/googleapis/api/httpbody"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Cmd int32

const (
	Cmd_CMD_BUY  Cmd = 0
	Cmd_CMD_SELL Cmd = 1
)

var Cmd_name = map[int32]string{
	0: "CMD_BUY",
	1: "CMD_SELL",
}

var Cmd_value = map[string]int32{
	"CMD_BUY":  0,
	"CMD_SELL": 1,
}

func (x Cmd) String() string {
	return proto.EnumName(Cmd_name, int32(x))
}

func (Cmd) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

type UserInfo struct {
	// Output only.
	Login    int32  `protobuf:"varint,1,opt,name=login,proto3" json:"login,omitempty"`
	Group    string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Name     string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Enabled  int32  `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Leverage int32  `protobuf:"varint,5,opt,name=leverage,proto3" json:"leverage,omitempty"`
	// Output only.
	Balance float64 `protobuf:"fixed64,6,opt,name=balance,proto3" json:"balance,omitempty"`
	// Output only.
	Credit               float64  `protobuf:"fixed64,7,opt,name=credit,proto3" json:"credit,omitempty"`
	AgentAccount         int32    `protobuf:"varint,8,opt,name=agent_account,json=agentAccount,proto3" json:"agent_account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

func (m *UserInfo) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserInfo) GetEnabled() int32 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func (m *UserInfo) GetLeverage() int32 {
	if m != nil {
		return m.Leverage
	}
	return 0
}

func (m *UserInfo) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *UserInfo) GetCredit() float64 {
	if m != nil {
		return m.Credit
	}
	return 0
}

func (m *UserInfo) GetAgentAccount() int32 {
	if m != nil {
		return m.AgentAccount
	}
	return 0
}

type UserInfoRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Login                int32    `protobuf:"varint,2,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfoRequest) Reset()         { *m = UserInfoRequest{} }
func (m *UserInfoRequest) String() string { return proto.CompactTextString(m) }
func (*UserInfoRequest) ProtoMessage()    {}
func (*UserInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *UserInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoRequest.Unmarshal(m, b)
}
func (m *UserInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoRequest.Marshal(b, m, deterministic)
}
func (m *UserInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoRequest.Merge(m, src)
}
func (m *UserInfoRequest) XXX_Size() int {
	return xxx_messageInfo_UserInfoRequest.Size(m)
}
func (m *UserInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoRequest proto.InternalMessageInfo

func (m *UserInfoRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UserInfoRequest) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

type UserInfoResponse struct {
	User                 *UserInfo `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Code                 int32     `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *UserInfoResponse) Reset()         { *m = UserInfoResponse{} }
func (m *UserInfoResponse) String() string { return proto.CompactTextString(m) }
func (*UserInfoResponse) ProtoMessage()    {}
func (*UserInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *UserInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfoResponse.Unmarshal(m, b)
}
func (m *UserInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfoResponse.Marshal(b, m, deterministic)
}
func (m *UserInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfoResponse.Merge(m, src)
}
func (m *UserInfoResponse) XXX_Size() int {
	return xxx_messageInfo_UserInfoResponse.Size(m)
}
func (m *UserInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfoResponse proto.InternalMessageInfo

func (m *UserInfoResponse) GetUser() *UserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserInfoResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UserInfoResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddUserInfo struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordInvestor     string   `protobuf:"bytes,3,opt,name=password_investor,json=passwordInvestor,proto3" json:"password_investor,omitempty"`
	Group                string   `protobuf:"bytes,4,opt,name=group,proto3" json:"group,omitempty"`
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Login                int32    `protobuf:"varint,6,opt,name=login,proto3" json:"login,omitempty"`
	Enabled              int32    `protobuf:"varint,7,opt,name=enabled,proto3" json:"enabled,omitempty"`
	City                 string   `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Phone                string   `protobuf:"bytes,9,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserInfo) Reset()         { *m = AddUserInfo{} }
func (m *AddUserInfo) String() string { return proto.CompactTextString(m) }
func (*AddUserInfo) ProtoMessage()    {}
func (*AddUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *AddUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserInfo.Unmarshal(m, b)
}
func (m *AddUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserInfo.Marshal(b, m, deterministic)
}
func (m *AddUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserInfo.Merge(m, src)
}
func (m *AddUserInfo) XXX_Size() int {
	return xxx_messageInfo_AddUserInfo.Size(m)
}
func (m *AddUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserInfo proto.InternalMessageInfo

func (m *AddUserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AddUserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AddUserInfo) GetPasswordInvestor() string {
	if m != nil {
		return m.PasswordInvestor
	}
	return ""
}

func (m *AddUserInfo) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

func (m *AddUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AddUserInfo) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

func (m *AddUserInfo) GetEnabled() int32 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func (m *AddUserInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *AddUserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

type AddUserRequest struct {
	Token                string                `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *AddUserInfo          `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AddUserRequest) Reset()         { *m = AddUserRequest{} }
func (m *AddUserRequest) String() string { return proto.CompactTextString(m) }
func (*AddUserRequest) ProtoMessage()    {}
func (*AddUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *AddUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserRequest.Unmarshal(m, b)
}
func (m *AddUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserRequest.Marshal(b, m, deterministic)
}
func (m *AddUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserRequest.Merge(m, src)
}
func (m *AddUserRequest) XXX_Size() int {
	return xxx_messageInfo_AddUserRequest.Size(m)
}
func (m *AddUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserRequest proto.InternalMessageInfo

func (m *AddUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AddUserRequest) GetUser() *AddUserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *AddUserRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type AddUserResponse struct {
	Login                int32    `protobuf:"varint,1,opt,name=login,proto3" json:"login,omitempty"`
	Code                 int32    `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddUserResponse) Reset()         { *m = AddUserResponse{} }
func (m *AddUserResponse) String() string { return proto.CompactTextString(m) }
func (*AddUserResponse) ProtoMessage()    {}
func (*AddUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *AddUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddUserResponse.Unmarshal(m, b)
}
func (m *AddUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddUserResponse.Marshal(b, m, deterministic)
}
func (m *AddUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddUserResponse.Merge(m, src)
}
func (m *AddUserResponse) XXX_Size() int {
	return xxx_messageInfo_AddUserResponse.Size(m)
}
func (m *AddUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddUserResponse proto.InternalMessageInfo

func (m *AddUserResponse) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

func (m *AddUserResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *AddUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateUserInfo struct {
	Login                int32    `protobuf:"varint,1,opt,name=login,proto3" json:"login,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Enabled              int32    `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=password,proto3" json:"password,omitempty"`
	PasswordInvestor     string   `protobuf:"bytes,6,opt,name=password_investor,json=passwordInvestor,proto3" json:"password_investor,omitempty"`
	Phone                string   `protobuf:"bytes,7,opt,name=phone,proto3" json:"phone,omitempty"`
	City                 string   `protobuf:"bytes,8,opt,name=city,proto3" json:"city,omitempty"`
	Group                string   `protobuf:"bytes,9,opt,name=group,proto3" json:"group,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserInfo) Reset()         { *m = UpdateUserInfo{} }
func (m *UpdateUserInfo) String() string { return proto.CompactTextString(m) }
func (*UpdateUserInfo) ProtoMessage()    {}
func (*UpdateUserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *UpdateUserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserInfo.Unmarshal(m, b)
}
func (m *UpdateUserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserInfo.Marshal(b, m, deterministic)
}
func (m *UpdateUserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserInfo.Merge(m, src)
}
func (m *UpdateUserInfo) XXX_Size() int {
	return xxx_messageInfo_UpdateUserInfo.Size(m)
}
func (m *UpdateUserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserInfo proto.InternalMessageInfo

func (m *UpdateUserInfo) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

func (m *UpdateUserInfo) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *UpdateUserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserInfo) GetEnabled() int32 {
	if m != nil {
		return m.Enabled
	}
	return 0
}

func (m *UpdateUserInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdateUserInfo) GetPasswordInvestor() string {
	if m != nil {
		return m.PasswordInvestor
	}
	return ""
}

func (m *UpdateUserInfo) GetPhone() string {
	if m != nil {
		return m.Phone
	}
	return ""
}

func (m *UpdateUserInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *UpdateUserInfo) GetGroup() string {
	if m != nil {
		return m.Group
	}
	return ""
}

type UpdateUserRequest struct {
	Token                string                `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *UpdateUserInfo       `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *UpdateUserRequest) GetUser() *UpdateUserInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type UpdateUserResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *UpdateUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type DeleteUserRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Login                int32    `protobuf:"varint,2,opt,name=login,proto3" json:"login,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *DeleteUserRequest) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

type DeleteUserResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

func (m *DeleteUserResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *DeleteUserResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type ResetPasswordInfo struct {
	Login                int32    `protobuf:"varint,1,opt,name=login,proto3" json:"login,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	PasswordInvestor     string   `protobuf:"bytes,3,opt,name=password_investor,json=passwordInvestor,proto3" json:"password_investor,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordInfo) Reset()         { *m = ResetPasswordInfo{} }
func (m *ResetPasswordInfo) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordInfo) ProtoMessage()    {}
func (*ResetPasswordInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *ResetPasswordInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordInfo.Unmarshal(m, b)
}
func (m *ResetPasswordInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordInfo.Marshal(b, m, deterministic)
}
func (m *ResetPasswordInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordInfo.Merge(m, src)
}
func (m *ResetPasswordInfo) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordInfo.Size(m)
}
func (m *ResetPasswordInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordInfo proto.InternalMessageInfo

func (m *ResetPasswordInfo) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

func (m *ResetPasswordInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ResetPasswordInfo) GetPasswordInvestor() string {
	if m != nil {
		return m.PasswordInvestor
	}
	return ""
}

type ResetPasswordRequest struct {
	Token                string                `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *ResetPasswordInfo    `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ResetPasswordRequest) Reset()         { *m = ResetPasswordRequest{} }
func (m *ResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordRequest) ProtoMessage()    {}
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *ResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordRequest.Unmarshal(m, b)
}
func (m *ResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *ResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordRequest.Merge(m, src)
}
func (m *ResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordRequest.Size(m)
}
func (m *ResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordRequest proto.InternalMessageInfo

func (m *ResetPasswordRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ResetPasswordRequest) GetUser() *ResetPasswordInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *ResetPasswordRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type ResetPasswordResponse struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResetPasswordResponse) Reset()         { *m = ResetPasswordResponse{} }
func (m *ResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ResetPasswordResponse) ProtoMessage()    {}
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *ResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResetPasswordResponse.Unmarshal(m, b)
}
func (m *ResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *ResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResetPasswordResponse.Merge(m, src)
}
func (m *ResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ResetPasswordResponse.Size(m)
}
func (m *ResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResetPasswordResponse proto.InternalMessageInfo

func (m *ResetPasswordResponse) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ResetPasswordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type FundsInfo struct {
	Login                int32    `protobuf:"varint,1,opt,name=login,proto3" json:"login,omitempty"`
	Amount               float64  `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	IsCredit             int32    `protobuf:"varint,3,opt,name=is_credit,json=isCredit,proto3" json:"is_credit,omitempty"`
	Comment              string   `protobuf:"bytes,4,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FundsInfo) Reset()         { *m = FundsInfo{} }
func (m *FundsInfo) String() string { return proto.CompactTextString(m) }
func (*FundsInfo) ProtoMessage()    {}
func (*FundsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *FundsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FundsInfo.Unmarshal(m, b)
}
func (m *FundsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FundsInfo.Marshal(b, m, deterministic)
}
func (m *FundsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FundsInfo.Merge(m, src)
}
func (m *FundsInfo) XXX_Size() int {
	return xxx_messageInfo_FundsInfo.Size(m)
}
func (m *FundsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_FundsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_FundsInfo proto.InternalMessageInfo

func (m *FundsInfo) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

func (m *FundsInfo) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *FundsInfo) GetIsCredit() int32 {
	if m != nil {
		return m.IsCredit
	}
	return 0
}

func (m *FundsInfo) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type FundsRequest struct {
	Token                string                `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	User                 *FundsInfo            `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *FundsRequest) Reset()         { *m = FundsRequest{} }
func (m *FundsRequest) String() string { return proto.CompactTextString(m) }
func (*FundsRequest) ProtoMessage()    {}
func (*FundsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *FundsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FundsRequest.Unmarshal(m, b)
}
func (m *FundsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FundsRequest.Marshal(b, m, deterministic)
}
func (m *FundsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FundsRequest.Merge(m, src)
}
func (m *FundsRequest) XXX_Size() int {
	return xxx_messageInfo_FundsRequest.Size(m)
}
func (m *FundsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FundsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FundsRequest proto.InternalMessageInfo

func (m *FundsRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *FundsRequest) GetUser() *FundsInfo {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *FundsRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type FundsResponse struct {
	Balance              float64  `protobuf:"fixed64,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Credit               float64  `protobuf:"fixed64,2,opt,name=credit,proto3" json:"credit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FundsResponse) Reset()         { *m = FundsResponse{} }
func (m *FundsResponse) String() string { return proto.CompactTextString(m) }
func (*FundsResponse) ProtoMessage()    {}
func (*FundsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *FundsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FundsResponse.Unmarshal(m, b)
}
func (m *FundsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FundsResponse.Marshal(b, m, deterministic)
}
func (m *FundsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FundsResponse.Merge(m, src)
}
func (m *FundsResponse) XXX_Size() int {
	return xxx_messageInfo_FundsResponse.Size(m)
}
func (m *FundsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FundsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FundsResponse proto.InternalMessageInfo

func (m *FundsResponse) GetBalance() float64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *FundsResponse) GetCredit() float64 {
	if m != nil {
		return m.Credit
	}
	return 0
}

type TradeInfo struct {
	Ticket               int32    `protobuf:"varint,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Login                int32    `protobuf:"varint,2,opt,name=login,proto3" json:"login,omitempty"`
	Symbol               string   `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Digits               int32    `protobuf:"varint,4,opt,name=digits,proto3" json:"digits,omitempty"`
	Cmd                  Cmd      `protobuf:"varint,5,opt,name=cmd,proto3,enum=api_pb.Cmd" json:"cmd,omitempty"`
	Volume               int32    `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	OpenTime             int32    `protobuf:"varint,7,opt,name=open_time,json=openTime,proto3" json:"open_time,omitempty"`
	State                int32    `protobuf:"varint,8,opt,name=state,proto3" json:"state,omitempty"`
	OpenPrice            float64  `protobuf:"fixed64,9,opt,name=open_price,json=openPrice,proto3" json:"open_price,omitempty"`
	Sl                   float64  `protobuf:"fixed64,10,opt,name=sl,proto3" json:"sl,omitempty"`
	Tp                   float64  `protobuf:"fixed64,11,opt,name=tp,proto3" json:"tp,omitempty"`
	CloseTime            int32    `protobuf:"varint,12,opt,name=close_time,json=closeTime,proto3" json:"close_time,omitempty"`
	Expiration           int32    `protobuf:"varint,13,opt,name=expiration,proto3" json:"expiration,omitempty"`
	Commission           float64  `protobuf:"fixed64,14,opt,name=commission,proto3" json:"commission,omitempty"`
	ClosePrice           float64  `protobuf:"fixed64,15,opt,name=close_price,json=closePrice,proto3" json:"close_price,omitempty"`
	Profit               float64  `protobuf:"fixed64,16,opt,name=profit,proto3" json:"profit,omitempty"`
	Magic                int32    `protobuf:"varint,17,opt,name=magic,proto3" json:"magic,omitempty"`
	Comment              string   `protobuf:"bytes,18,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TradeInfo) Reset()         { *m = TradeInfo{} }
func (m *TradeInfo) String() string { return proto.CompactTextString(m) }
func (*TradeInfo) ProtoMessage()    {}
func (*TradeInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *TradeInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TradeInfo.Unmarshal(m, b)
}
func (m *TradeInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TradeInfo.Marshal(b, m, deterministic)
}
func (m *TradeInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TradeInfo.Merge(m, src)
}
func (m *TradeInfo) XXX_Size() int {
	return xxx_messageInfo_TradeInfo.Size(m)
}
func (m *TradeInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TradeInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TradeInfo proto.InternalMessageInfo

func (m *TradeInfo) GetTicket() int32 {
	if m != nil {
		return m.Ticket
	}
	return 0
}

func (m *TradeInfo) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

func (m *TradeInfo) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *TradeInfo) GetDigits() int32 {
	if m != nil {
		return m.Digits
	}
	return 0
}

func (m *TradeInfo) GetCmd() Cmd {
	if m != nil {
		return m.Cmd
	}
	return Cmd_CMD_BUY
}

func (m *TradeInfo) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *TradeInfo) GetOpenTime() int32 {
	if m != nil {
		return m.OpenTime
	}
	return 0
}

func (m *TradeInfo) GetState() int32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *TradeInfo) GetOpenPrice() float64 {
	if m != nil {
		return m.OpenPrice
	}
	return 0
}

func (m *TradeInfo) GetSl() float64 {
	if m != nil {
		return m.Sl
	}
	return 0
}

func (m *TradeInfo) GetTp() float64 {
	if m != nil {
		return m.Tp
	}
	return 0
}

func (m *TradeInfo) GetCloseTime() int32 {
	if m != nil {
		return m.CloseTime
	}
	return 0
}

func (m *TradeInfo) GetExpiration() int32 {
	if m != nil {
		return m.Expiration
	}
	return 0
}

func (m *TradeInfo) GetCommission() float64 {
	if m != nil {
		return m.Commission
	}
	return 0
}

func (m *TradeInfo) GetClosePrice() float64 {
	if m != nil {
		return m.ClosePrice
	}
	return 0
}

func (m *TradeInfo) GetProfit() float64 {
	if m != nil {
		return m.Profit
	}
	return 0
}

func (m *TradeInfo) GetMagic() int32 {
	if m != nil {
		return m.Magic
	}
	return 0
}

func (m *TradeInfo) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type OpenTradeRequest struct {
	Login                int32    `protobuf:"varint,1,opt,name=login,proto3" json:"login,omitempty"`
	Symbol               string   `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Cmd                  Cmd      `protobuf:"varint,3,opt,name=cmd,proto3,enum=api_pb.Cmd" json:"cmd,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Slippage             int32    `protobuf:"varint,5,opt,name=slippage,proto3" json:"slippage,omitempty"`
	Sl                   float64  `protobuf:"fixed64,6,opt,name=sl,proto3" json:"sl,omitempty"`
	Tp                   float64  `protobuf:"fixed64,7,opt,name=tp,proto3" json:"tp,omitempty"`
	Volume               int32    `protobuf:"varint,8,opt,name=volume,proto3" json:"volume,omitempty"`
	Comment              string   `protobuf:"bytes,9,opt,name=comment,proto3" json:"comment,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenTradeRequest) Reset()         { *m = OpenTradeRequest{} }
func (m *OpenTradeRequest) String() string { return proto.CompactTextString(m) }
func (*OpenTradeRequest) ProtoMessage()    {}
func (*OpenTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{18}
}

func (m *OpenTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenTradeRequest.Unmarshal(m, b)
}
func (m *OpenTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenTradeRequest.Marshal(b, m, deterministic)
}
func (m *OpenTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenTradeRequest.Merge(m, src)
}
func (m *OpenTradeRequest) XXX_Size() int {
	return xxx_messageInfo_OpenTradeRequest.Size(m)
}
func (m *OpenTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OpenTradeRequest proto.InternalMessageInfo

func (m *OpenTradeRequest) GetLogin() int32 {
	if m != nil {
		return m.Login
	}
	return 0
}

func (m *OpenTradeRequest) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *OpenTradeRequest) GetCmd() Cmd {
	if m != nil {
		return m.Cmd
	}
	return Cmd_CMD_BUY
}

func (m *OpenTradeRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *OpenTradeRequest) GetSlippage() int32 {
	if m != nil {
		return m.Slippage
	}
	return 0
}

func (m *OpenTradeRequest) GetSl() float64 {
	if m != nil {
		return m.Sl
	}
	return 0
}

func (m *OpenTradeRequest) GetTp() float64 {
	if m != nil {
		return m.Tp
	}
	return 0
}

func (m *OpenTradeRequest) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

func (m *OpenTradeRequest) GetComment() string {
	if m != nil {
		return m.Comment
	}
	return ""
}

type OpenTradeResponse struct {
	Ticket               int32    `protobuf:"varint,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message              string   `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OpenTradeResponse) Reset()         { *m = OpenTradeResponse{} }
func (m *OpenTradeResponse) String() string { return proto.CompactTextString(m) }
func (*OpenTradeResponse) ProtoMessage()    {}
func (*OpenTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{19}
}

func (m *OpenTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OpenTradeResponse.Unmarshal(m, b)
}
func (m *OpenTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OpenTradeResponse.Marshal(b, m, deterministic)
}
func (m *OpenTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OpenTradeResponse.Merge(m, src)
}
func (m *OpenTradeResponse) XXX_Size() int {
	return xxx_messageInfo_OpenTradeResponse.Size(m)
}
func (m *OpenTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OpenTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OpenTradeResponse proto.InternalMessageInfo

func (m *OpenTradeResponse) GetTicket() int32 {
	if m != nil {
		return m.Ticket
	}
	return 0
}

func (m *OpenTradeResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *OpenTradeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type UpdateTradeRequest struct {
	Ticket               int32    `protobuf:"varint,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Price                float64  `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Sl                   float64  `protobuf:"fixed64,6,opt,name=sl,proto3" json:"sl,omitempty"`
	Tp                   float64  `protobuf:"fixed64,7,opt,name=tp,proto3" json:"tp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTradeRequest) Reset()         { *m = UpdateTradeRequest{} }
func (m *UpdateTradeRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateTradeRequest) ProtoMessage()    {}
func (*UpdateTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{20}
}

func (m *UpdateTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTradeRequest.Unmarshal(m, b)
}
func (m *UpdateTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTradeRequest.Marshal(b, m, deterministic)
}
func (m *UpdateTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTradeRequest.Merge(m, src)
}
func (m *UpdateTradeRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateTradeRequest.Size(m)
}
func (m *UpdateTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTradeRequest proto.InternalMessageInfo

func (m *UpdateTradeRequest) GetTicket() int32 {
	if m != nil {
		return m.Ticket
	}
	return 0
}

func (m *UpdateTradeRequest) GetPrice() float64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *UpdateTradeRequest) GetSl() float64 {
	if m != nil {
		return m.Sl
	}
	return 0
}

func (m *UpdateTradeRequest) GetTp() float64 {
	if m != nil {
		return m.Tp
	}
	return 0
}

type UpdateTradeResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateTradeResponse) Reset()         { *m = UpdateTradeResponse{} }
func (m *UpdateTradeResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateTradeResponse) ProtoMessage()    {}
func (*UpdateTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{21}
}

func (m *UpdateTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateTradeResponse.Unmarshal(m, b)
}
func (m *UpdateTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateTradeResponse.Marshal(b, m, deterministic)
}
func (m *UpdateTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateTradeResponse.Merge(m, src)
}
func (m *UpdateTradeResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateTradeResponse.Size(m)
}
func (m *UpdateTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateTradeResponse proto.InternalMessageInfo

func (m *UpdateTradeResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *UpdateTradeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CloseTradeRequest struct {
	Ticket               int32    `protobuf:"varint,1,opt,name=ticket,proto3" json:"ticket,omitempty"`
	Volume               int32    `protobuf:"varint,2,opt,name=volume,proto3" json:"volume,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseTradeRequest) Reset()         { *m = CloseTradeRequest{} }
func (m *CloseTradeRequest) String() string { return proto.CompactTextString(m) }
func (*CloseTradeRequest) ProtoMessage()    {}
func (*CloseTradeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{22}
}

func (m *CloseTradeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseTradeRequest.Unmarshal(m, b)
}
func (m *CloseTradeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseTradeRequest.Marshal(b, m, deterministic)
}
func (m *CloseTradeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseTradeRequest.Merge(m, src)
}
func (m *CloseTradeRequest) XXX_Size() int {
	return xxx_messageInfo_CloseTradeRequest.Size(m)
}
func (m *CloseTradeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseTradeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CloseTradeRequest proto.InternalMessageInfo

func (m *CloseTradeRequest) GetTicket() int32 {
	if m != nil {
		return m.Ticket
	}
	return 0
}

func (m *CloseTradeRequest) GetVolume() int32 {
	if m != nil {
		return m.Volume
	}
	return 0
}

type CloseTradeResponse struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CloseTradeResponse) Reset()         { *m = CloseTradeResponse{} }
func (m *CloseTradeResponse) String() string { return proto.CompactTextString(m) }
func (*CloseTradeResponse) ProtoMessage()    {}
func (*CloseTradeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{23}
}

func (m *CloseTradeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CloseTradeResponse.Unmarshal(m, b)
}
func (m *CloseTradeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CloseTradeResponse.Marshal(b, m, deterministic)
}
func (m *CloseTradeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CloseTradeResponse.Merge(m, src)
}
func (m *CloseTradeResponse) XXX_Size() int {
	return xxx_messageInfo_CloseTradeResponse.Size(m)
}
func (m *CloseTradeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CloseTradeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CloseTradeResponse proto.InternalMessageInfo

func (m *CloseTradeResponse) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *CloseTradeResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("api_pb.Cmd", Cmd_name, Cmd_value)
	proto.RegisterType((*UserInfo)(nil), "api_pb.UserInfo")
	proto.RegisterType((*UserInfoRequest)(nil), "api_pb.UserInfoRequest")
	proto.RegisterType((*UserInfoResponse)(nil), "api_pb.UserInfoResponse")
	proto.RegisterType((*AddUserInfo)(nil), "api_pb.AddUserInfo")
	proto.RegisterType((*AddUserRequest)(nil), "api_pb.AddUserRequest")
	proto.RegisterType((*AddUserResponse)(nil), "api_pb.AddUserResponse")
	proto.RegisterType((*UpdateUserInfo)(nil), "api_pb.UpdateUserInfo")
	proto.RegisterType((*UpdateUserRequest)(nil), "api_pb.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "api_pb.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "api_pb.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "api_pb.DeleteUserResponse")
	proto.RegisterType((*ResetPasswordInfo)(nil), "api_pb.ResetPasswordInfo")
	proto.RegisterType((*ResetPasswordRequest)(nil), "api_pb.ResetPasswordRequest")
	proto.RegisterType((*ResetPasswordResponse)(nil), "api_pb.ResetPasswordResponse")
	proto.RegisterType((*FundsInfo)(nil), "api_pb.FundsInfo")
	proto.RegisterType((*FundsRequest)(nil), "api_pb.FundsRequest")
	proto.RegisterType((*FundsResponse)(nil), "api_pb.FundsResponse")
	proto.RegisterType((*TradeInfo)(nil), "api_pb.TradeInfo")
	proto.RegisterType((*OpenTradeRequest)(nil), "api_pb.OpenTradeRequest")
	proto.RegisterType((*OpenTradeResponse)(nil), "api_pb.OpenTradeResponse")
	proto.RegisterType((*UpdateTradeRequest)(nil), "api_pb.UpdateTradeRequest")
	proto.RegisterType((*UpdateTradeResponse)(nil), "api_pb.UpdateTradeResponse")
	proto.RegisterType((*CloseTradeRequest)(nil), "api_pb.CloseTradeRequest")
	proto.RegisterType((*CloseTradeResponse)(nil), "api_pb.CloseTradeResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 1374 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4f, 0x6f, 0x1b, 0x45,
	0x14, 0x67, 0xed, 0x64, 0x6d, 0x3f, 0xe7, 0x8f, 0x3d, 0x4d, 0x9c, 0xad, 0x9b, 0xd0, 0x68, 0x29,
	0xa2, 0x2a, 0x22, 0x91, 0xcc, 0xad, 0x50, 0x41, 0xe2, 0xb6, 0xa8, 0xa8, 0x85, 0xca, 0x6d, 0x54,
	0xc1, 0x01, 0x6b, 0xbd, 0x3b, 0x71, 0x47, 0xd9, 0xdd, 0x59, 0x76, 0xc6, 0x29, 0x05, 0x7a, 0x80,
	0x13, 0x07, 0x4e, 0x70, 0xe1, 0xc4, 0x07, 0xe1, 0x6b, 0x70, 0x40, 0xe2, 0x0a, 0x1f, 0x00, 0x89,
	0x2f, 0x80, 0xe6, 0xcf, 0xae, 0x67, 0xfd, 0xaf, 0x49, 0xc9, 0x6d, 0xdf, 0x7b, 0x3b, 0xef, 0xcf,
	0xef, 0xf7, 0x66, 0xde, 0x83, 0x9a, 0x97, 0x90, 0xbd, 0x24, 0xa5, 0x9c, 0x22, 0xdb, 0x4b, 0x48,
	0x3f, 0x19, 0xb4, 0xb7, 0x87, 0x94, 0x0e, 0x43, 0xbc, 0xef, 0x25, 0x64, 0xdf, 0x8b, 0x63, 0xca,
	0x3d, 0x4e, 0x68, 0xcc, 0xd4, 0x5f, 0xb9, 0x55, 0x4a, 0x83, 0xd1, 0xf1, 0x3e, 0xe3, 0xe9, 0xc8,
	0xe7, 0xda, 0x7a, 0xd9, 0x38, 0xfb, 0x94, 0xf3, 0x64, 0x40, 0x83, 0xe7, 0xda, 0x74, 0x65, 0xf2,
	0x20, 0x8e, 0x12, 0x9e, 0x19, 0xb7, 0x4e, 0xbd, 0x90, 0x04, 0x1e, 0xc7, 0xfb, 0xd9, 0x87, 0x36,
	0xec, 0x4e, 0x9e, 0x3a, 0x26, 0x38, 0x0c, 0xfa, 0x91, 0xc7, 0x4e, 0xd4, 0x1f, 0xee, 0x1f, 0x16,
	0x54, 0x8f, 0x18, 0x4e, 0xef, 0xc5, 0xc7, 0x14, 0x6d, 0xc0, 0x72, 0x48, 0x87, 0x24, 0x76, 0xac,
	0x5d, 0xeb, 0xfa, 0x72, 0x4f, 0x09, 0x42, 0x3b, 0x4c, 0xe9, 0x28, 0x71, 0x4a, 0xbb, 0xd6, 0xf5,
	0x5a, 0x4f, 0x09, 0x08, 0xc1, 0x52, 0xec, 0x45, 0xd8, 0x29, 0x4b, 0xa5, 0xfc, 0x46, 0x0e, 0x54,
	0x70, 0xec, 0x0d, 0x42, 0x1c, 0x38, 0x4b, 0xd2, 0x43, 0x26, 0xa2, 0x36, 0x54, 0x43, 0x7c, 0x8a,
	0x53, 0x6f, 0x88, 0x9d, 0x65, 0x69, 0xca, 0x65, 0x71, 0x6a, 0xe0, 0x85, 0x5e, 0xec, 0x63, 0xc7,
	0xde, 0xb5, 0xae, 0x5b, 0xbd, 0x4c, 0x44, 0x2d, 0xb0, 0xfd, 0x14, 0x07, 0x84, 0x3b, 0x15, 0x69,
	0xd0, 0x12, 0x7a, 0x03, 0x56, 0xbd, 0x21, 0x8e, 0x79, 0xdf, 0xf3, 0x7d, 0x3a, 0x8a, 0xb9, 0x53,
	0x95, 0x2e, 0x57, 0xa4, 0xf2, 0x40, 0xe9, 0xdc, 0x5b, 0xb0, 0x9e, 0x15, 0xd6, 0xc3, 0x5f, 0x8e,
	0x30, 0xe3, 0xa2, 0x12, 0x4e, 0x4f, 0xb0, 0xaa, 0xaf, 0xd6, 0x53, 0xc2, 0xb8, 0xea, 0x92, 0x51,
	0xb5, 0x7b, 0x0c, 0x8d, 0xf1, 0x71, 0x96, 0xd0, 0x98, 0x61, 0x74, 0x0d, 0x96, 0x46, 0x0c, 0xa7,
	0xf2, 0x78, 0xbd, 0xd3, 0xd8, 0x53, 0x94, 0xef, 0xe5, 0xff, 0x49, 0xab, 0x40, 0xc6, 0xa7, 0x01,
	0xd6, 0xee, 0xe4, 0xb7, 0xa8, 0x31, 0xc2, 0x8c, 0x89, 0xf2, 0x15, 0x60, 0x99, 0xe8, 0xfe, 0x63,
	0x41, 0xfd, 0x20, 0x08, 0x4c, 0x0e, 0x70, 0xe4, 0x91, 0x30, 0xcb, 0x51, 0x0a, 0x02, 0xbf, 0xc4,
	0x63, 0xec, 0x19, 0x4d, 0x03, 0x4d, 0x43, 0x2e, 0xa3, 0xb7, 0xa1, 0x99, 0x7d, 0xf7, 0x49, 0x7c,
	0x8a, 0x19, 0xa7, 0xa9, 0x8e, 0xd2, 0xc8, 0x0c, 0xf7, 0xb4, 0x7e, 0x4c, 0xe6, 0xd2, 0x2c, 0x32,
	0x97, 0x0d, 0x32, 0x73, 0x58, 0x6c, 0xb3, 0x19, 0x0c, 0x8a, 0x2b, 0x45, 0x8a, 0x45, 0xd9, 0x84,
	0x3f, 0x97, 0x5c, 0xd4, 0x7a, 0xf2, 0x5b, 0xf8, 0x48, 0x9e, 0xd2, 0x18, 0x3b, 0x35, 0x15, 0x4d,
	0x0a, 0xee, 0x8f, 0x16, 0xac, 0xe9, 0x92, 0x17, 0x33, 0xf3, 0x96, 0xc6, 0xbb, 0x24, 0xf1, 0xbe,
	0x94, 0xe1, 0x6d, 0xc0, 0xa5, 0x21, 0x7f, 0x0f, 0xea, 0xa3, 0x44, 0xf4, 0xbd, 0x6c, 0x6d, 0x59,
	0x7c, 0xbd, 0xd3, 0xde, 0x53, 0xdd, 0xbf, 0x97, 0x75, 0xff, 0xde, 0x5d, 0xd1, 0xfd, 0x0f, 0x3c,
	0x76, 0xd2, 0x03, 0xf5, 0xbb, 0xf8, 0x76, 0x8f, 0x60, 0x3d, 0xcf, 0x46, 0x13, 0x3d, 0xfb, 0x22,
	0x9c, 0x8f, 0xd8, 0x7f, 0x2d, 0x58, 0x3b, 0x92, 0x51, 0x5e, 0x7e, 0xbf, 0x14, 0xe3, 0x25, 0x93,
	0xf1, 0x73, 0xdf, 0xaf, 0xbc, 0x3f, 0x96, 0xcf, 0xd2, 0x1f, 0xf6, 0xfc, 0xfe, 0x50, 0x8c, 0x55,
	0x0c, 0xc6, 0xe6, 0x71, 0xab, 0x3a, 0xa9, 0x66, 0x74, 0x92, 0xfb, 0x93, 0x05, 0xcd, 0x71, 0xd5,
	0x8b, 0xe9, 0xbd, 0x51, 0xa0, 0xb7, 0x95, 0x5f, 0xa7, 0x02, 0x68, 0x17, 0xc1, 0xf0, 0x21, 0x20,
	0x33, 0x27, 0x4d, 0x72, 0x46, 0xa7, 0x35, 0x9b, 0xce, 0x52, 0x91, 0xce, 0x0f, 0xa0, 0x79, 0x1b,
	0x87, 0xf8, 0x2c, 0x75, 0xcd, 0x7e, 0x50, 0x0e, 0x01, 0x99, 0x0e, 0x5e, 0x29, 0x89, 0x14, 0x9a,
	0x3d, 0xcc, 0x30, 0x7f, 0x98, 0xd3, 0x36, 0xb7, 0xab, 0x2e, 0xea, 0xc5, 0x70, 0x7f, 0xb1, 0x60,
	0xa3, 0x10, 0x74, 0x71, 0xf1, 0xef, 0x14, 0x48, 0xbd, 0x9c, 0x91, 0x3a, 0x95, 0xf6, 0x45, 0xf0,
	0x7a, 0x07, 0x36, 0x27, 0x32, 0x7b, 0x25, 0x54, 0x13, 0xa8, 0xdd, 0x1d, 0xc5, 0x01, 0x5b, 0x80,
	0x66, 0x0b, 0x6c, 0x2f, 0x92, 0xa3, 0xa6, 0xa4, 0x26, 0x91, 0x92, 0xd0, 0x15, 0xa8, 0x11, 0xd6,
	0xd7, 0x43, 0xaa, 0xac, 0x06, 0x1b, 0x61, 0x5d, 0x35, 0xa6, 0x1c, 0xa8, 0xf8, 0x34, 0x8a, 0x70,
	0xcc, 0xf5, 0x6b, 0x9b, 0x89, 0xee, 0x0f, 0x16, 0xac, 0xc8, 0x90, 0x8b, 0xb1, 0x7c, 0xb3, 0x80,
	0x65, 0x33, 0xc3, 0x32, 0x4f, 0xf6, 0x22, 0x30, 0x3c, 0x80, 0x55, 0x9d, 0x89, 0xc6, 0xce, 0x18,
	0xc7, 0xd6, 0xbc, 0x71, 0x5c, 0x32, 0xc7, 0xb1, 0xfb, 0x67, 0x19, 0x6a, 0x8f, 0x53, 0x2f, 0xc0,
	0x12, 0xc0, 0x16, 0xd8, 0x9c, 0xf8, 0x27, 0x98, 0x6b, 0x04, 0xb5, 0x34, 0xfb, 0x56, 0x88, 0xbf,
	0xd9, 0xf3, 0x68, 0x40, 0x43, 0xdd, 0x7f, 0x5a, 0x12, 0xfa, 0x80, 0x0c, 0x09, 0x67, 0xfa, 0xa5,
	0xd3, 0x12, 0xda, 0x81, 0xb2, 0x1f, 0xa9, 0x37, 0x6e, 0xad, 0x53, 0xcf, 0x10, 0xe9, 0x46, 0x41,
	0x4f, 0xe8, 0xc5, 0xb1, 0x53, 0x1a, 0x8e, 0x22, 0xac, 0xa7, 0x96, 0x96, 0x04, 0x4f, 0x34, 0xc1,
	0x71, 0x9f, 0x93, 0x08, 0xeb, 0xc1, 0x55, 0x15, 0x8a, 0xc7, 0x44, 0x4d, 0x3a, 0xc6, 0x3d, 0x8e,
	0xf5, 0x1a, 0xa1, 0x04, 0xb4, 0x03, 0x20, 0x8f, 0x24, 0x29, 0xf1, 0xd5, 0x00, 0xb3, 0x7a, 0xd2,
	0xc9, 0x43, 0xa1, 0x40, 0x6b, 0x50, 0x62, 0xa1, 0x03, 0x52, 0x5d, 0x62, 0xa1, 0x90, 0x79, 0xe2,
	0xd4, 0x95, 0xcc, 0x13, 0x71, 0xdc, 0x0f, 0x29, 0xc3, 0x2a, 0xe4, 0x8a, 0xf4, 0x5c, 0x93, 0x1a,
	0x19, 0xf3, 0x75, 0x00, 0xfc, 0x55, 0x42, 0x52, 0xb9, 0x1d, 0x3a, 0xab, 0xd2, 0x6c, 0x68, 0x84,
	0x5d, 0x34, 0x0b, 0x61, 0x4c, 0xd8, 0xd7, 0xa4, 0x5b, 0x43, 0x83, 0xae, 0x42, 0x5d, 0xb9, 0x57,
	0xe9, 0xad, 0xeb, 0x1f, 0x84, 0x4a, 0xe5, 0xd7, 0x02, 0x3b, 0x49, 0xe9, 0x31, 0xe1, 0x4e, 0x43,
	0x91, 0xa5, 0x24, 0x51, 0x6c, 0xe4, 0x0d, 0x89, 0xef, 0x34, 0x55, 0xb1, 0x52, 0x30, 0x5b, 0x15,
	0x15, 0x5b, 0xf5, 0x2f, 0x0b, 0x1a, 0x9f, 0x0a, 0xa4, 0x04, 0xc1, 0x46, 0xbb, 0xce, 0xbe, 0x24,
	0x9a, 0xcb, 0x52, 0x81, 0x4b, 0xcd, 0x59, 0x79, 0x0e, 0x67, 0x62, 0xe4, 0xc8, 0x22, 0x96, 0x64,
	0xa2, 0x4a, 0x10, 0xef, 0x17, 0x0b, 0x49, 0x92, 0x18, 0x1b, 0x63, 0x26, 0x6b, 0xec, 0xed, 0x09,
	0xec, 0x2b, 0x39, 0xf6, 0xe3, 0x2e, 0xa8, 0x16, 0xba, 0xc0, 0xa8, 0xb2, 0x56, 0xac, 0x32, 0x80,
	0xa6, 0x51, 0xa4, 0xbe, 0x09, 0xf3, 0x3a, 0x79, 0x07, 0x00, 0xa7, 0x29, 0x4d, 0xfb, 0xc6, 0x36,
	0x50, 0x93, 0x9a, 0xee, 0xe2, 0x95, 0x60, 0x90, 0xcd, 0xa1, 0x02, 0x98, 0x0b, 0x2e, 0xcc, 0x0c,
	0x5c, 0x5e, 0x52, 0xbb, 0xfb, 0x09, 0x5c, 0x2a, 0xc4, 0xd0, 0xb5, 0x14, 0x73, 0xb6, 0x16, 0xe4,
	0x3c, 0xf1, 0x38, 0x76, 0xa1, 0xd9, 0x95, 0x5d, 0x7b, 0x96, 0x94, 0xc7, 0xc0, 0x97, 0x4c, 0xe0,
	0xdd, 0x07, 0x80, 0x4c, 0x27, 0xff, 0x33, 0xa7, 0x1b, 0xbb, 0x50, 0xee, 0x46, 0x01, 0xaa, 0x43,
	0xa5, 0xfb, 0xe0, 0x76, 0xff, 0xf0, 0xe8, 0xb3, 0xc6, 0x6b, 0x68, 0x05, 0xaa, 0x42, 0x78, 0x74,
	0xe7, 0xfe, 0xfd, 0x86, 0xd5, 0xf9, 0xcd, 0x86, 0xba, 0x98, 0xb3, 0x8f, 0x70, 0x7a, 0x2a, 0x50,
	0x7b, 0x04, 0x95, 0x8f, 0x30, 0x97, 0xef, 0xd3, 0xd6, 0xd4, 0xda, 0xae, 0x8a, 0x6a, 0x3b, 0xd3,
	0x06, 0x95, 0xa8, 0xbb, 0xf9, 0xfd, 0xef, 0x7f, 0xff, 0x5c, 0x5a, 0x47, 0xab, 0xfb, 0xe2, 0xbd,
	0xdd, 0xff, 0x46, 0xb6, 0xfb, 0x0b, 0xf4, 0x05, 0xd8, 0x6a, 0xa2, 0xa3, 0x7c, 0xcc, 0x4d, 0xad,
	0x08, 0xed, 0xf6, 0x2c, 0x93, 0xf6, 0xbb, 0x23, 0xfd, 0x6e, 0xdd, 0xd8, 0xd4, 0x7e, 0xe5, 0xab,
	0xff, 0x22, 0xf7, 0xff, 0x04, 0xca, 0x07, 0x41, 0x80, 0x5a, 0x13, 0x7b, 0x6f, 0xe6, 0x79, 0x6b,
	0x4a, 0xaf, 0xdd, 0x5e, 0x95, 0x6e, 0x2f, 0xbb, 0x4d, 0xe5, 0xd6, 0x0b, 0x82, 0xcc, 0xf5, 0x4d,
	0x35, 0x30, 0xbe, 0xb3, 0xc0, 0x56, 0x4d, 0x32, 0xce, 0x7c, 0x6a, 0x69, 0x1b, 0x67, 0x3e, 0xbd,
	0x3b, 0xb9, 0x1f, 0xca, 0x10, 0x37, 0xdb, 0x1b, 0x2a, 0x84, 0x9a, 0x27, 0xc5, 0x28, 0x9f, 0x6f,
	0x77, 0x16, 0x58, 0xd1, 0xb7, 0x50, 0x7d, 0x42, 0xf8, 0xd3, 0x20, 0xf5, 0x9e, 0xa1, 0x8d, 0xc2,
	0x64, 0xcb, 0xe2, 0x6f, 0x4e, 0x68, 0x75, 0xe8, 0xae, 0x0c, 0x7d, 0xab, 0xdd, 0x52, 0xce, 0x9f,
	0x69, 0x27, 0x13, 0xc1, 0x77, 0x3a, 0x9b, 0x63, 0xfb, 0x94, 0x19, 0x7d, 0x0d, 0x95, 0xdb, 0x38,
	0xa1, 0x4c, 0x3c, 0x88, 0xe7, 0x09, 0x7e, 0x28, 0x83, 0xbf, 0xdf, 0xd6, 0xce, 0x03, 0xe5, 0x63,
	0x5e, 0xec, 0x99, 0x66, 0xf4, 0xab, 0x05, 0xab, 0x85, 0xb5, 0x05, 0x6d, 0xcf, 0xdc, 0x92, 0xb2,
	0x54, 0x76, 0xe6, 0x58, 0x75, 0x4a, 0x0f, 0x65, 0x4a, 0x1f, 0xb7, 0xb7, 0x55, 0xcc, 0x54, 0xfc,
	0xd4, 0xcf, 0xb6, 0xb8, 0x89, 0xcc, 0xae, 0x75, 0xce, 0xf0, 0xd7, 0xc0, 0x96, 0x2b, 0xc3, 0xbb,
	0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xf7, 0x7f, 0xd3, 0x08, 0xde, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	GetInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error)
	Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	Add(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error)
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	Withdraw(ctx context.Context, in *FundsRequest, opts ...grpc.CallOption) (*FundsResponse, error)
	Deposit(ctx context.Context, in *FundsRequest, opts ...grpc.CallOption) (*FundsResponse, error)
	ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) GetInfo(ctx context.Context, in *UserInfoRequest, opts ...grpc.CallOption) (*UserInfoResponse, error) {
	out := new(UserInfoResponse)
	err := c.cc.Invoke(ctx, "/api_pb.UserService/GetInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/api_pb.UserService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Add(ctx context.Context, in *AddUserRequest, opts ...grpc.CallOption) (*AddUserResponse, error) {
	out := new(AddUserResponse)
	err := c.cc.Invoke(ctx, "/api_pb.UserService/Add", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/api_pb.UserService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Withdraw(ctx context.Context, in *FundsRequest, opts ...grpc.CallOption) (*FundsResponse, error) {
	out := new(FundsResponse)
	err := c.cc.Invoke(ctx, "/api_pb.UserService/Withdraw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Deposit(ctx context.Context, in *FundsRequest, opts ...grpc.CallOption) (*FundsResponse, error) {
	out := new(FundsResponse)
	err := c.cc.Invoke(ctx, "/api_pb.UserService/Deposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordRequest, opts ...grpc.CallOption) (*ResetPasswordResponse, error) {
	out := new(ResetPasswordResponse)
	err := c.cc.Invoke(ctx, "/api_pb.UserService/ResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	GetInfo(context.Context, *UserInfoRequest) (*UserInfoResponse, error)
	Delete(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	Add(context.Context, *AddUserRequest) (*AddUserResponse, error)
	Update(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	Withdraw(context.Context, *FundsRequest) (*FundsResponse, error)
	Deposit(context.Context, *FundsRequest) (*FundsResponse, error)
	ResetPassword(context.Context, *ResetPasswordRequest) (*ResetPasswordResponse, error)
}

// UnimplementedUserServiceServer can be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (*UnimplementedUserServiceServer) GetInfo(ctx context.Context, req *UserInfoRequest) (*UserInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetInfo not implemented")
}
func (*UnimplementedUserServiceServer) Delete(ctx context.Context, req *DeleteUserRequest) (*DeleteUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedUserServiceServer) Add(ctx context.Context, req *AddUserRequest) (*AddUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Add not implemented")
}
func (*UnimplementedUserServiceServer) Update(ctx context.Context, req *UpdateUserRequest) (*UpdateUserResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (*UnimplementedUserServiceServer) Withdraw(ctx context.Context, req *FundsRequest) (*FundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Withdraw not implemented")
}
func (*UnimplementedUserServiceServer) Deposit(ctx context.Context, req *FundsRequest) (*FundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Deposit not implemented")
}
func (*UnimplementedUserServiceServer) ResetPassword(ctx context.Context, req *ResetPasswordRequest) (*ResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPassword not implemented")
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_pb.UserService/GetInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetInfo(ctx, req.(*UserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_pb.UserService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Delete(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_pb.UserService/Add",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Add(ctx, req.(*AddUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_pb.UserService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Withdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Withdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_pb.UserService/Withdraw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Withdraw(ctx, req.(*FundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_pb.UserService/Deposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Deposit(ctx, req.(*FundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api_pb.UserService/ResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ResetPassword(ctx, req.(*ResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api_pb.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _UserService_GetInfo_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _UserService_Delete_Handler,
		},
		{
			MethodName: "Add",
			Handler:    _UserService_Add_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _UserService_Update_Handler,
		},
		{
			MethodName: "Withdraw",
			Handler:    _UserService_Withdraw_Handler,
		},
		{
			MethodName: "Deposit",
			Handler:    _UserService_Deposit_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _UserService_ResetPassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
